# Generated by Django 5.1.7 on 2025-06-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(default='code', help_text='Font Awesome icon class (e.g., python, js, html5)', max_length=50),
        ),
    ]
